<template>
  <div class="container">
    <router-outlet></router-outlet
    ><provably-fair-layout class="provably-fair-page ng-star-inserted" v-if="$route.params.article == 'description'">
      <ProvablyFair v-bind:detailed="true"/>
      <div
        class="provably-fair-page__content content"
        
      >
        <div scroll="vertical" class="content__scroll scroll scroll_vertical">
          <router-outlet></router-outlet
          ><provably-fair-description
            _nghost-serverapp-c230=""
            class="ng-star-inserted"
            ><div _ngcontent-serverapp-c230="" class="content__paragraph">
              <h2 _ngcontent-serverapp-c230="" class="content__subtitle">
                Generating the result of game modes
              </h2>
              <p _ngcontent-serverapp-c230="" class="content__text">
                In game modes Crash, Wheel, Double - the result of each round is
                generated on the clients of four different and independent
                devices that participate in a particular round. These include
                the game server and the three players who made the first bet.
              </p>
              <p _ngcontent-serverapp-c230="" class="content__text">
                At the start of the round, the game combines the server seed and
                client seeds of the first 3 players. Merged seeds generate
                <span _ngcontent-serverapp-c230="">SHA256</span> hash, and
                generated hash already determines the outcome of a particular
                round.
              </p>
              <p _ngcontent-serverapp-c230="" class="content__text">
                To participate in the formation of the result of the round, you
                need to be among the first three players who make a bet in a
                particular round.
              </p>
              <p _ngcontent-serverapp-c230="" class="content__text">
                In the Jackpot game mode - system, a salt (32 random symbols)
                and a number from 0 to 1 are randomly generated. They are added
                together and hashed with
                <span _ngcontent-serverapp-c230="">sha256</span>, the hash is
                available to all players on the game page before placing a bet.
              </p>
              <p _ngcontent-serverapp-c230="" class="content__text">
                Each player is given 1 ticket for every $0.01 (1 cent). At the
                end of the game, the winning ticket is selected according to the
                formula: bank * 100 * round number. Whoever has this ticket
                wins.
              </p>
              <p _ngcontent-serverapp-c230="" class="content__text">
                In the history of the game, you can see the salt with which the
                generation was made, and make sure that the hash is unchanged.
                You can decrypt the hash on any SHA256 generator site or on our
                page
                <a
                  _ngcontent-serverapp-c230=""
                  routerlink="/provably-fair/realization"
                  class="content__link"
                  href="/en/provably-fair/realization"
                  >/provably-fair/realization</a
                >
              </p>
            </div>
            <div _ngcontent-serverapp-c230="" class="content__paragraph">
              <h2 _ngcontent-serverapp-c230="" class="content__subtitle">
                Server Seed
              </h2>
              <p _ngcontent-serverapp-c230="" class="content__text">
                The server seed is generated by our system as a random string of
                44 characters. We provide an encrypted hash of the generated
                number before the start of the round, its value is on game page.
                Write down the hash before you place a bet, so you make sure the
                value remains the same and you can calculate result after the
                end of the round.
              </p>
              <p _ngcontent-serverapp-c230="" class="content__text">
                After the game, you can verify the fairness of the round by
                checking the hash of the server seed in the calculator on our
                page
                <a
                  _ngcontent-serverapp-c230=""
                  routerlink="/provably-fair/realization"
                  class="content__link"
                  href="/en/provably-fair/realization"
                  >/provably-fair/realization</a
                >
              </p>
            </div>
            <div _ngcontent-serverapp-c230="" class="content__paragraph">
              <h2 _ngcontent-serverapp-c230="" class="content__subtitle">
                Client Seed
              </h2>
              <p _ngcontent-serverapp-c230="" class="content__text">
                The client seed is generated on the device of each user of the
                game and can be replaced with a personal one (any character set
                at the user's discretion). The client seed is used to ensure
                that the result is completely randomly generated.
              </p>
              <p _ngcontent-serverapp-c230="" class="content__text">
                This mechanism provides transparency and honesty in generation
                of game results. If there were no client seeds during the
                formation of the final hash, only the server seed would
                influence the formation of the result of the game.
              </p>
            </div>
            <div _ngcontent-serverapp-c230="" class="content__paragraph">
              <h2 _ngcontent-serverapp-c230="" class="content__subtitle">
                Crash
              </h2>
              <p _ngcontent-serverapp-c230="" class="content__text">
                Gabe continues to run to the coefficient calculated using the
                players participating in the round according to the formula:
              </p>
            </div>
            <pre
              _ngcontent-serverapp-c230=""
            >  <code _ngcontent-serverapp-c230="" class="scroll code__scroll hljs"><span class="hljs-keyword">const</span> sha256 = <span class="hljs-comment">/* any javascript sha256 library */</span>;

<span class="hljs-keyword">const</span> concatenatedString = serverSeed + userSeedOne + userSeedTwo + userSeedThree;
<span class="hljs-keyword">const</span> hash = <span class="hljs-title function_">sha256</span>(concatenatedString).<span class="hljs-title function_">toString</span>();
<span class="hljs-keyword">const</span> hex = hash.<span class="hljs-title function_">substring</span>(<span class="hljs-number">0</span>, <span class="hljs-number">8</span>);
<span class="hljs-keyword">const</span> dec = <span class="hljs-built_in">parseInt</span>(hex, <span class="hljs-number">16</span>);

<span class="hljs-keyword">let</span> ratio = <span class="hljs-number">2</span> ** <span class="hljs-number">32</span> / (dec + <span class="hljs-number">1</span>) * (<span class="hljs-number">1</span> - <span class="hljs-number">0.01</span>);

ratio = <span class="hljs-title class_">Number</span>(ratio.<span class="hljs-title function_">toFixed</span>(<span class="hljs-number">2</span>));
ratio = <span class="hljs-title class_">Math</span>.<span class="hljs-title function_">max</span>(<span class="hljs-number">1</span>, ratio);

<span class="hljs-variable language_">console</span>.<span class="hljs-title function_">log</span>(ratio);</code>
</pre>
            <div _ngcontent-serverapp-c230="" class="content__paragraph">
              <h2 _ngcontent-serverapp-c230="" class="content__subtitle">
                Wheel
              </h2>
              <p _ngcontent-serverapp-c230="" class="content__text">
                Each wheel color is tied to a sector number. Sector numbers are
                not displayed in the game module, but they can be checked on
                this page.
              </p>
              <p _ngcontent-serverapp-c230="" class="content__text">
                Blue color (2x) - 2; 4; 6; 8; 10; 12; 14; 16; 18; 20; 22; 24;
                26; 28; 30; 32; 34; 36; 38; 40; 42; 44; 46; 48; 50; 52
              </p>
              <p _ngcontent-serverapp-c230="" class="content__text">
                Green color (3x) - 3; 5; 7; 13; 15; 17; 23; 25; 27; 29; 31; 37;
                39; 41; 47; 49; 51
              </p>
              <p _ngcontent-serverapp-c230="" class="content__text">
                Purple color (5x) - 1; 9; 11; 19; 21; 33; 35; 43; 45; 53
              </p>
              <p _ngcontent-serverapp-c230="" class="content__text">
                Gold color (20x) - 0
              </p>
              <p _ngcontent-serverapp-c230="" class="content__text">
                The winning sector number is calculated using the players
                participating in the round according to the formula:
              </p>
            </div>
            <pre
              _ngcontent-serverapp-c230=""
            >  <code _ngcontent-serverapp-c230="" class="scroll code__scroll hljs"><span class="hljs-keyword">const</span> sha256 = <span class="hljs-comment">/* any javascript sha256 library */</span>;

<span class="hljs-keyword">const</span> concatenatedString = serverSeed + userSeedOne + userSeedTwo + userSeedThree;
<span class="hljs-keyword">const</span> hash = <span class="hljs-title function_">sha256</span>(concatenatedString).<span class="hljs-title function_">toString</span>();
<span class="hljs-keyword">const</span> hex = hash.<span class="hljs-title function_">substring</span>(<span class="hljs-number">0</span>, <span class="hljs-number">8</span>);
<span class="hljs-keyword">const</span> dec = <span class="hljs-built_in">parseInt</span>(hex, <span class="hljs-number">16</span>);

<span class="hljs-keyword">const</span> number = <span class="hljs-title class_">Math</span>.<span class="hljs-title function_">floor</span>((dec / <span class="hljs-number">16</span> ** <span class="hljs-number">8</span>) * <span class="hljs-number">54</span>);

<span class="hljs-variable language_">console</span>.<span class="hljs-title function_">log</span>(number);
</code>
</pre>
            <div _ngcontent-serverapp-c230="" class="content__paragraph">
              <h2 _ngcontent-serverapp-c230="" class="content__subtitle">
                Double
              </h2>
              <p _ngcontent-serverapp-c230="" class="content__text">
                Each color on the reel is tied to a sector number:
              </p>
              <p _ngcontent-serverapp-c230="" class="content__text">
                Red color (2х) - 1; 2; 3; 4; 5; 6; 7
              </p>
              <p _ngcontent-serverapp-c230="" class="content__text">
                Green color (14х) - 0
              </p>
              <p _ngcontent-serverapp-c230="" class="content__text">
                Black color (2х) - 8; 9; 10; 11; 12; 13; 14
              </p>
              <p _ngcontent-serverapp-c230="" class="content__text">
                The winning sector number is calculated using the players
                participating in the round according to the formula:
              </p>
            </div>
            <pre
              _ngcontent-serverapp-c230=""
            >  <code _ngcontent-serverapp-c230="" class="scroll code__scroll hljs"><span class="hljs-keyword">const</span> sha256 = <span class="hljs-comment">/* any javascript sha256 library */</span>;

<span class="hljs-keyword">const</span> concatenatedString = serverSeed + userSeedOne + userSeedTwo + userSeedThree;
<span class="hljs-keyword">const</span> hash = <span class="hljs-title function_">sha256</span>(concatenatedString).<span class="hljs-title function_">toString</span>();
<span class="hljs-keyword">const</span> hex = hash.<span class="hljs-title function_">substring</span>(<span class="hljs-number">0</span>, <span class="hljs-number">8</span>);
<span class="hljs-keyword">const</span> dec = <span class="hljs-built_in">parseInt</span>(hex, <span class="hljs-number">16</span>);

<span class="hljs-keyword">const</span> number = <span class="hljs-title class_">Math</span>.<span class="hljs-title function_">floor</span>((dec / <span class="hljs-number">16</span> ** <span class="hljs-number">8</span>) * <span class="hljs-number">15</span>);

<span class="hljs-variable language_">console</span>.<span class="hljs-title function_">log</span>(number);
</code>
</pre>
            <div _ngcontent-serverapp-c230="" class="content__paragraph">
              <h2 _ngcontent-serverapp-c230="" class="content__subtitle">
                Jackpot
              </h2>
              <p _ngcontent-serverapp-c230="" class="content__text">
                The number of the round, with the help of which the winning
                ticket is subsequently selected, is generated by the formula:
              </p>
            </div>
            <pre
              _ngcontent-serverapp-c230=""
            >  <code _ngcontent-serverapp-c230="" class="scroll code__scroll hljs"><span class="hljs-keyword">const</span> sha256 = <span class="hljs-comment">/* any javascript sha256 library */</span>;
<span class="hljs-keyword">const</span> gameBankUsd = <span class="hljs-number">100</span>; <span class="hljs-comment">/* or any real game bank */</span>

<span class="hljs-keyword">function</span> <span class="hljs-title function_">getRandomArbitrary</span>(<span class="hljs-params">min, max</span>) {
  <span class="hljs-keyword">return</span> <span class="hljs-title class_">Math</span>.<span class="hljs-title function_">random</span>() * (max - min) + min;
}

<span class="hljs-keyword">function</span> <span class="hljs-title function_">dec2hex</span>(<span class="hljs-params">dec</span>) {
  <span class="hljs-keyword">return</span> dec.<span class="hljs-title function_">toString</span>(<span class="hljs-number">16</span>).<span class="hljs-title function_">padStart</span>(<span class="hljs-number">2</span>, <span class="hljs-string">'0'</span>);
}

<span class="hljs-keyword">function</span> <span class="hljs-title function_">genSalt</span>(<span class="hljs-params">len</span>) {
  <span class="hljs-keyword">const</span> arr = <span class="hljs-keyword">new</span> <span class="hljs-title class_">Uint8Array</span>((len || <span class="hljs-number">40</span>) / <span class="hljs-number">2</span>);
  <span class="hljs-variable language_">window</span>.<span class="hljs-property">crypto</span>.<span class="hljs-title function_">getRandomValues</span>(arr);
  <span class="hljs-keyword">return</span> <span class="hljs-title class_">Array</span>.<span class="hljs-title function_">from</span>(arr, dec2hex).<span class="hljs-title function_">join</span>(<span class="hljs-string">''</span>);
}

<span class="hljs-keyword">const</span> roundNumber = <span class="hljs-title function_">getRandomArbitrary</span>(<span class="hljs-number">0</span>, <span class="hljs-number">1000000000</span>) / <span class="hljs-number">1000000000</span>;
<span class="hljs-keyword">const</span> salt = <span class="hljs-title function_">genSalt</span>(<span class="hljs-number">32</span>);
<span class="hljs-keyword">const</span> string = roundNumber +<span class="hljs-string">'+'</span>+ salt;

<span class="hljs-keyword">const</span> hash = <span class="hljs-title function_">sha256</span>(string);
<span class="hljs-keyword">const</span> winTicket = <span class="hljs-title class_">Math</span>.<span class="hljs-title function_">floor</span>(<span class="hljs-title class_">Number</span>(gameBankUsd) * <span class="hljs-number">100</span> * <span class="hljs-title class_">Number</span>(roundNumber));

<span class="hljs-variable language_">console</span>.<span class="hljs-title function_">log</span>(hash, winTicket);</code>
</pre>
          </provably-fair-description>
        </div>
      </div>

      
    </provably-fair-layout>
    <provably-fair-layout class="provably-fair-page ng-star-inserted" v-if="$route.params.article == 'realization'">
        <ProvablyFair v-bind:realization="true"/>
        <div
        class="provably-fair-page__content content"
        
      >
        <div scroll="vertical" class="content__scroll scroll scroll_vertical">
          <router-outlet></router-outlet
          ><provably-fair-realization class="provably-fair-realization"
            ><form novalidate="" class="ng-untouched ng-pristine ng-valid">
              <div class="content__check check">
                <div
                  dropdown=""
                  dropdownopenclass="is-open"
                  class="check__modes dropdown"
                  :class="{'is-open': DropDownGames}"
                  @click="DropDownGames = !DropDownGames"
                >
                  <div dropdowntoggle="" class="dropdown__head dropdown-head">
                    <div class="dropdown-head__game game" v-if="SelectGame.crash">
                        <img src="../../../public/images/icon/coupon1.png"  class="icon_bonus_small">
                      <div class="game__info">
                        <div class="game__name">Game</div>
                        <div class="game__title">Crash</div>
                      </div>
                    </div>
                    <div class="dropdown-head__game game" v-else-if="SelectGame.jackpot">
                        <img src="../../../public/images/icon/trending-topic.png"  class="icon_bonus_small">
                      <div class="game__info">
                        <div class="game__name">Game</div>
                        <div class="game__title">Jackpot</div>
                      </div>
                    </div>
                    <div class="dropdown-head__game game" v-else-if="SelectGame.wheel">
                        <img src="../../../public/images/icon/spinning-wheel.png"  class="icon_bonus_small">
                      <div class="game__info">
                        <div class="game__name">Game</div>
                        <div class="game__title">Wheel</div>
                      </div>
                    </div>
                    <div class="dropdown-head__game game" v-else-if="SelectGame.double">
                        <img src="../../../public/images/icon/double.png"  class="icon_bonus_small">
                      <div class="game__info">
                        <div class="game__name">Game</div>
                        <div class="game__title">Double</div>
                      </div>
                    </div>
                  </div>
                  <div dropdowncontent="" class="dropdown__options">
                    <div class="dropdown__option game" :class="{'is-active': SelectGame.crash}" @click="SelectGame.crash=true, SelectGame.jackpot=false, SelectGame.wheel=false, SelectGame.double=false">
                      <div class="game__icon"><img src="../../../public/images/icon/coupon1.png" class="icon_bonus_small"></div>
                      <div class="game__title">Crash</div>
                    </div>
                    <div class="dropdown__option game" :class="{'is-active': SelectGame.jackpot}" @click="SelectGame.crash=false, SelectGame.jackpot=true, SelectGame.wheel=false, SelectGame.double=false">
                      <div class="game__icon"><img src="../../../public/images/icon/trending-topic.png" class="icon_bonus_small"></div>
                      <div class="game__title">Jackpot</div>
                    </div>
                    <div class="dropdown__option game" :class="{'is-active': SelectGame.wheel}" @click="SelectGame.crash=false, SelectGame.jackpot=false, SelectGame.wheel=true, SelectGame.double=false">
                      <div class="game__icon"><img src="../../../public/images/icon/spinning-wheel.png" class="icon_bonus_small"></div>
                      <div class="game__title">Wheel</div>
                    </div>
                    <div class="dropdown__option game" :class="{'is-active': SelectGame.double}" @click="SelectGame.crash=false, SelectGame.jackpot=false, SelectGame.wheel=false, SelectGame.double=true">
                      <div class="game__icon"><img src="../../../public/images/icon/double.png" class="icon_bonus_small"></div>
                      <div class="game__title">Double</div>
                    </div>
                  </div>
                </div>
                <div class="check__by-id">
                  <div class="check__input">
                    <label for="gameId" class="check__input-title"
                      >Game number</label
                    ><input
                      type="number"
                      name="gameId"
                      id="gameId"
                      placeholder="Enter the game number"
                      class="check__input-value ng-untouched ng-pristine ng-valid"
                    />
                  </div>
                  <button
                    type="button"
                    class="button button_block check__button"
                    disabled=""
                  >
                    Find game
                  </button>
                </div>
                <realization-form-crash _nghost-serverapp-c149=""
                  ><form
                    _ngcontent-serverapp-c149=""
                    novalidate=""
                    class="realization-form ng-untouched ng-pristine ng-valid"
                  >
                    <provably-fair-input
                      _ngcontent-serverapp-c149=""
                      title="Server seed"
                      placeholder="Enter server seed"
                      fieldname="serverSeed"
                      class="check__col ng-untouched ng-pristine ng-valid"
                      _nghost-serverapp-c148=""
                      ><div
                        _ngcontent-serverapp-c148=""
                        class="check__input ng-untouched ng-pristine ng-valid"
                      >
                        <label
                          _ngcontent-serverapp-c148=""
                          class="check__input-title"
                          for="serverSeed"
                        >
                          Server seed </label
                        ><input
                          _ngcontent-serverapp-c148=""
                          class="check__input-value ng-untouched ng-pristine ng-valid"
                          id="serverSeed"
                          type="text"
                          placeholder="Enter server seed"
                        /></div></provably-fair-input
                    ><provably-fair-input
                      _ngcontent-serverapp-c149=""
                      title="Seed 1"
                      placeholder="Enter seed 1"
                      fieldname="userSeedOne"
                      class="check__col ng-untouched ng-pristine ng-valid"
                      _nghost-serverapp-c148=""
                      ><div
                        _ngcontent-serverapp-c148=""
                        class="check__input ng-untouched ng-pristine ng-valid"
                      >
                        <label
                          _ngcontent-serverapp-c148=""
                          class="check__input-title"
                          for="userSeedOne"
                        >
                          Seed 1 </label
                        ><input
                          _ngcontent-serverapp-c148=""
                          class="check__input-value ng-untouched ng-pristine ng-valid"
                          id="userSeedOne"
                          type="text"
                          placeholder="Enter seed 1"
                        /></div></provably-fair-input
                    ><provably-fair-input
                      _ngcontent-serverapp-c149=""
                      title="Seed 2"
                      placeholder="Enter seed 2"
                      fieldname="userSeedTwo"
                      class="check__col ng-untouched ng-pristine ng-valid"
                      _nghost-serverapp-c148=""
                      ><div
                        _ngcontent-serverapp-c148=""
                        class="check__input ng-untouched ng-pristine ng-valid"
                      >
                        <label
                          _ngcontent-serverapp-c148=""
                          class="check__input-title"
                          for="userSeedTwo"
                        >
                          Seed 2 </label
                        ><input
                          _ngcontent-serverapp-c148=""
                          class="check__input-value ng-untouched ng-pristine ng-valid"
                          id="userSeedTwo"
                          type="text"
                          placeholder="Enter seed 2"
                        /></div></provably-fair-input
                    ><provably-fair-input
                      _ngcontent-serverapp-c149=""
                      title="Seed 3"
                      placeholder="Enter seed 3"
                      fieldname="userSeedThree"
                      class="check__col ng-untouched ng-pristine ng-valid"
                      _nghost-serverapp-c148=""
                      ><div
                        _ngcontent-serverapp-c148=""
                        class="check__input ng-untouched ng-pristine ng-valid"
                      >
                        <label
                          _ngcontent-serverapp-c148=""
                          class="check__input-title"
                          for="userSeedThree"
                        >
                          Seed 3 </label
                        ><input
                          _ngcontent-serverapp-c148=""
                          class="check__input-value ng-untouched ng-pristine ng-valid"
                          id="userSeedThree"
                          type="text"
                          placeholder="Enter seed 3"
                        /></div
                    ></provably-fair-input>
                    <div _ngcontent-serverapp-c149="" class="check__coeff">
                      x0
                    </div>
                  </form>
                </realization-form-crash>
              </div>
            </form>
          </provably-fair-realization>
        </div>
      </div>
    </provably-fair-layout>
  </div>

  <Footer />
</template>

<script>
import Footer from "../../components/Footer";
import ProvablyFair from "../../components/ProvablyFair";

export default {
  components: {
    Footer,
    ProvablyFair,
  },
  data() {
    return {
        DropDownGames: false,
        SelectGame: {crash: true, jackpot: false, wheel: false, double: false}
    }
  }
};
</script>

<style>
:root {
  --gutter: 2rem;
  --gutter-page: 4rem;
  --gutter-shop: 2.5rem;
  --gutter-support: 2.5rem;
}
@media all and (max-width: 991px) {
  :root {
    --gutter: 1.5rem;
    --gutter-page: 2rem;
  }
}
.provably-fair-realization .realization-form {
  display: grid;
  grid-template-columns: 1fr 44%;
  gap: 1.1rem 2rem;
}
.provably-fair-realization .realization-form .check__col {
  grid-column: 1;
}
.provably-fair-realization .realization-form .check__coeff {
  grid-column: 2;
  grid-row: 1/4;
}
.provably-fair-realization .check {
  margin-bottom: 1.4rem;
}
.provably-fair-realization .check__modes {
  width: 100%;
}
.provably-fair-realization .check__by-id {
  display: flex;
  align-items: flex-end;
  margin-bottom: 2rem;
}
.provably-fair-realization .check__hexdec {
  display: flex;
  gap: 1rem;
  justify-content: space-between;
}
.provably-fair-realization .check__hexdec .form__group {
  width: 100%;
}
@media (max-width: 768px) {
  .provably-fair-realization .check__hexdec {
    display: block;
  }
}
.provably-fair-realization .check__round-data {
  margin-top: 2rem;
}
.provably-fair-realization .table {
  display: block;
  width: 100%;
  height: auto;
  padding-bottom: 0.4rem;
  overflow: auto hidden;
  margin: 2rem 0;
  font-size: 1.2rem;
}
.provably-fair-realization .table .image {
  width: 2rem;
  height: 2rem;
  margin-top: 2rem;
}
.provably-fair-realization .table table {
  width: 100%;
  border-radius: 1rem;
  overflow: hidden;
}
.provably-fair-realization .table tbody tr td {
  background-color: #394470;
}
.provably-fair-realization .table tbody tr:nth-child(odd) td {
  background-color: #3d4874;
}
.provably-fair-realization .table th,
.provably-fair-realization .table td {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  text-align: left;
  vertical-align: middle;
}
.provably-fair-realization .table th {
  height: 4.4rem;
  padding: 0 1rem;
  background-color: #394470;
  color: #7b84ab;
  font-size: 1.2rem;
  font-weight: 500;
  line-height: 4.4rem;
  text-transform: uppercase;
}
.provably-fair-realization .table th:first-child {
  padding-left: 2rem;
}
.provably-fair-realization .table th:last-child {
  border: 0;
  padding-right: 2rem;
}
.provably-fair-realization .table td {
  color: #b0b5cb;
  height: 4.4rem;
  padding: 0 1rem;
  line-height: 4.4rem;
}
.provably-fair-realization .table td:first-child {
  padding-left: 2rem;
}
.provably-fair-realization .table td:last-child {
  padding-right: 2rem;
}
.provably-fair-realization .table .mute {
  color: #a0ade2;
}
.provably-fair-realization .table .bold {
  color: #d6daec;
  font-weight: 600;
}
.provably-fair-realization .table {
  scrollbar-color: #2d365b #374270;
  scrollbar-width: 0.6rem;
  transform: translateZ(0);
  will-change: transform;
}
.provably-fair-realization .table::-webkit-scrollbar {
  width: 0.6rem;
  height: 0.6rem;
  background-color: #374270;
}
.provably-fair-realization .table::-webkit-scrollbar-thumb {
  background-color: #374270;
  border-radius: 10px;
}
.provably-fair-realization .table::-webkit-scrollbar-track {
  background-color: #2d365b;
}
.provably-fair-realization .check__button {
  background-color: #62d5b2;
  border-color: #62d5b2;
  color: #20274b;
  margin-left: 1.5rem;
  height: 5.8rem;
  width: 20rem;
  transition: background-color 0.2s ease-out 0s, border-color 0.2s ease-out 0s;
}
.provably-fair-realization .check__button:hover {
  background-color: #89e6ca;
  border-color: #89e6ca;
}
.provably-fair-realization .check__or {
  text-align: center;
  margin-top: 1rem;
  font-size: 1.2rem;
  color: #7781b6;
}
.provably-fair-realization .check__coeff {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
  background: rgba(122, 202, 247, 0.06);
  border: 0.1rem dashed rgba(133, 165, 226, 0.22);
  -webkit-backdrop-filter: blur(1.2rem);
  backdrop-filter: blur(1.2rem);
  border-radius: 2rem;
  font-weight: 300;
  font-size: 6rem;
  line-height: 1;
  color: #b7cbfe;
}
.provably-fair-realization .check__input {
  display: flex;
  flex-direction: column;
  width: 100%;
  gap: 0.8rem;
}
.provably-fair-realization .check__input .check__input-title {
  font-weight: 500;
  font-size: 1.4rem;
  line-height: 1.7rem;
  color: #7a89b9;
}
.provably-fair-realization .check__input .check__input-value {
  padding: 1.4rem 1.4rem 1.4rem 1.9rem;
  width: 100%;
  height: 5.8rem;
  background-color: #1f2a51;
  border: none;
  border-radius: 1rem;
  color: #dce5fb;
  transition: background-color 0.2s ease-out 0s;
  max-width: 100%;
  white-space: nowrap;
  text-overflow: ellipsis;
  overflow: hidden;
}
.provably-fair-realization .check__input .check__input-value,
.provably-fair-realization .check__input .check__input-value::placeholder {
  font-weight: 400;
  font-size: 1.7rem;
  line-height: 2.1rem;
}
.provably-fair-realization .check__input .check__input-value::placeholder {
  color: #7584bb;
}
.provably-fair-realization .check__input .check__input-value:hover,
.provably-fair-realization .check__input .check__input-value:focus {
  background-color: #202c55;
}
.provably-fair-realization .dropdown {
  position: relative;
  z-index: 1;
  margin-bottom: 1.1rem;
}
.provably-fair-realization .dropdown.is-open .dropdown__head {
  background-color: #354271;
}
.provably-fair-realization .dropdown.is-open .dropdown__head:after {
  transform: rotate(180deg);
}
.provably-fair-realization .dropdown.is-open .dropdown__options {
  transform: translateY(0);
  opacity: 1;
  visibility: visible;
}
.provably-fair-realization .dropdown .dropdown__head {
  display: flex;
  align-items: center;
  width: 100%;
  height: 5.8rem;
  padding-left: 1.6rem;
  background-color: #2f3c69;
  border-radius: 1rem;
  cursor: pointer;
  transition: background-color 0.2s ease-out 0s;
}
.provably-fair-realization .dropdown .dropdown__head:after {
  content: "";
  position: absolute;
  right: 1.6rem;
  display: block;
  margin: auto;
  border-left: 0.5rem solid rgba(0, 0, 0, 0);
  border-right: 0.5rem solid rgba(0, 0, 0, 0);
  border-top: 0.7rem solid #7b89b5;
  transition: transform 0.2s ease-out 0s;
}
.provably-fair-realization .dropdown .dropdown__head:hover {
  background-color: #354271;
}
.provably-fair-realization .dropdown .dropdown-head__placeholder {
  font-weight: 600;
  font-size: 1.4rem;
  line-height: 1.8rem;
  text-transform: uppercase;
  color: #8598d6;
}
.provably-fair-realization .dropdown .dropdown-head__game.game {
  display: flex;
  align-items: center;
  gap: 0.7rem;
}
.provably-fair-realization .dropdown .dropdown-head__game.game .game__icon {
  font-size: 2.6rem;
  color: #a1b2e7;
}
.provably-fair-realization .dropdown .dropdown-head__game.game .game__info {
  display: flex;
  flex-direction: column;
  gap: 0.2rem;
}
.provably-fair-realization .dropdown .dropdown-head__game.game .game__name {
  font-weight: 600;
  font-size: 1.2rem;
  line-height: 1;
  text-transform: uppercase;
  color: #a1b2e7;
}
.provably-fair-realization .dropdown .dropdown-head__game.game .game__title {
  font-weight: 600;
  font-size: 1.6rem;
  line-height: 1;
  text-transform: uppercase;
  color: #e8eeff;
}
.provably-fair-realization .dropdown .dropdown__options {
  position: absolute;
  bottom: -9.5rem;
  display: flex;
  gap: 0.4rem;
  width: 100%;
  height: auto;
  padding: 1.5rem;
  background: #313f6d;
  border-radius: 1rem;
  transform: translateY(-1rem);
  opacity: 0;
  visibility: hidden;
  transition: transform 0.2s ease-out 0s, opacity 0.2s ease-out 0s,
    visibility 0.2s ease-out 0s;
}
.provably-fair-realization .dropdown .dropdown__option.game {
  display: flex;
  align-items: center;
  gap: 0.7rem;
  height: 5.8rem;
  width: 100%;
  padding: 0 1.4rem;
  background: rgba(59, 73, 125, 0.6);
  border: 0.1rem solid transparent;
  border-color: #404e89;
  border-radius: 0.6rem;
  cursor: pointer;
  -webkit-user-select: none;
  user-select: none;
  transition: background 0.2s ease-out 0s, border-color 0.2s ease-out 0s;
}
.provably-fair-realization .dropdown .dropdown__option.game:hover,
.provably-fair-realization .dropdown .dropdown__option.game.is-active {
  background: rgba(72, 88, 145, 0.6);
  border-color: #526099;
}
.provably-fair-realization .dropdown .dropdown__option.game:hover .game__icon,
.provably-fair-realization
  .dropdown
  .dropdown__option.game.is-active
  .game__icon {
  --gradient-color1: #bccaf7;
  --gradient-color2: #bccaf7;
}
.provably-fair-realization .dropdown .dropdown__option.game:hover .game__title,
.provably-fair-realization
  .dropdown
  .dropdown__option.game.is-active
  .game__title {
  color: #f8faff;
}
.provably-fair-realization .dropdown .dropdown__option.game .game__icon {
  --gradient-color1: #59699f;
  --gradient-color2: #b8c5f2;
  font-size: 2.4rem;
  background: linear-gradient(
    180deg,
    var(--gradient-color1) 0%,
    var(--gradient-color2) 100%
  );
  -webkit-background-clip: text;
  background-clip: text;
  -webkit-text-fill-color: transparent;
  transition: --gradient-color1 0.2s ease-out 0s,
    --gradient-color2 0.2s ease-out 0s;
}
.provably-fair-realization .dropdown .dropdown__option.game .game__title {
  font-weight: 600;
  font-size: 1.4rem;
  line-height: 1.8rem;
  text-transform: uppercase;
  color: #c0cef1;
  transition: color 0.2s ease-out 0s;
}
@media all and (max-width: 767px) {
  .provably-fair-realization .check__modes {
    width: 100%;
  }
  .provably-fair-realization .check__coeff {
    height: 5.8rem;
    border-radius: 1rem;
    font-size: 3rem;
    margin-top: 0;
  }
  .provably-fair-realization .realization-form {
    grid-template-columns: 1fr;
  }
  .provably-fair-realization .realization-form .check__coeff {
    grid-column: 1;
    grid-row: 1;
  }
  .provably-fair-realization .dropdown .dropdown__options {
    bottom: -27.5rem;
    flex-wrap: wrap;
    height: auto;
  }
}
</style>